-- 点検種別マスターデータ追加SQL
-- Supabase SQL Editorで実行してください

INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('給水ポンプ点検', 'water_supply_pump_construction', '点検のため、マンション内に点検員が立ち入りいたします。断水はありませんが点検完了後、濁り水が出る場合があります。その際はしばらく流してご使用ください。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('携帯アンテナ工事', 'construction_mobile_antenna', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('宅配ボックス使用停止中', 'delivery_box_stop_using', 'ご不便をおかけいたしています。対応中ですのでもうしばらくお待ちください。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('共用部の排水管洗浄', 'shared_area_drain_pipe_wash', '共用部の排水管洗浄を行います。工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('消防設備連結管耐圧試験', 'shared_area_drain_pipe_inspection', '耐圧試験のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('外壁タイル工事', 'construction_outer wall', '作業には音と振動を伴います。また物の搬入のため車両を駐車いたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('カードリーダー更新工事', 'card_reader', '工事中に、オートロックが反応しない場合は別の出入り口に頂きますよう、お願い致します。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('エレベータマット取替工事', 'elevator_mat_replacement', '作業中はエレベーターのご利用を停止致します。\nご不便をおかけします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('エレベーター保守作業', 'elevator_inspection', '作業中はエレベーターのご利用を停止致します。\nご不便をおかけします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('作業のため作業員が入ります', 'construction_without_sound', '工事のためマンション敷地内に作業員が立ち入ります。また荷物搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('消防設備点検アンケート', 'questionnaire_conducted01', '消防点検のアンケートを配布しております。ご協力お願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('消防設備工事アンケート', 'questionnaire_conducted01', '消防設備改修のための、のアンケートを配布しております。ご協力お願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('排水管洗浄アンケート', 'questionnaire_conducted01', '排水管洗浄のアンケートを配布しております。ご協力お願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('インターホン工事アンケート', 'questionnaire_conducted01', 'インターホン取替工事のアンケートを配布しております。ご協力お願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('入居者様アンケート', 'questionnaire_conducted02', 'アンケート結果は、今後の物件企画・開発の為に参考にさせて頂きます。ご協力お願い致します。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('1年点検アンケート', 'questionnaire_conducted02', '竣工1年目のアフター点検のアンケートを配布しております。ご協力お願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('2年点検アンケート', 'questionnaire_conducted02', '竣工2年目のアフター点検のアンケートを配布しております。ご協力お願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('大規模修繕工事アンケート', 'questionnaire_conducted02', '大規模修繕に伴うアンケートを配布しております。ご協力お願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('チャリチャリ設置工事', 'merchari_installation', 'マンションに、シェアサイクルのポートを設置しております');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('消防訓練掲示', 'fire_extinguisher_explain', '訓練中に、放送、警報が鳴る場合がございます');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('ターンテーブル点検', 'mechanical_parking_turntable', '作業状況によっては入出庫に多少お待ち頂く場合がございます。\n入出庫の際は作業員へお声をかけて頂きますよう、お願い致します。\n＊雨天・緊急等の場合　順延する場合があります。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('建築設備調査', 'building_inspection', '点検のため、マンション内に調査員が立ち入りいたします。雨天の場合　順延する場合があります。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('コインパーキング工事', 'construction_coin_parking', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('活水装置工事', 'water_activator_construction', '断水中は蛇口を閉めて下さい。断水中に蛇口を開けると、閉め忘れて漏水事故の恐れがあります。断水前に飲料水等の必要な水の確保をお願いします。トイレご排水にはお風呂の汲み置きが有効です。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('インターホン工事', 'construction_Intercom', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('共用部照明工事', 'construction_light', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('カードリーダー工事', 'card_reader', '工事のため,カードリーダーが使用できません。作業には音と振動を伴います。皆様のご理解をお願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('連結送水管耐圧試験', 'shared_area_drain_pipe_inspection', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('大規模修繕工事', 'construction_building_large_scale', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('視聴設備更新工事', 'construction_television_equipment', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('JCOMケーブル工事', 'construction_jcom_cable', '点検のため、マンション内に調査員が立ち入りいたします。雨天の場合　順延する場合があります。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('消防改修工事', 'fire_construction', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('有線放送工事', 'construction_toolbox', '工事のためマンション敷地内に作業員が立ち入ります。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('ガラス清掃', 'glass_clean', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('特定防火対象物点検', 'building_inspection', '点検のため、マンション内に調査員が立ち入りいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('シャッター点検', 'electrical_measurement', '点検のため、マンション内に調査員が立ち入りいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('電子掲示板メンテナンス', 'construction_toolbox', '点検のため、建物内に作業員が立ち入りいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('空冷設備点検', 'building_inspection', '点検のため、建物内に作業員が立ち入りいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('全熱交換器点検', 'building_inspection', '点検のため、建物内に作業員が立ち入りいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('自動制御装置点検', 'building_inspection', '調査のため、建物内に調査員が立ち入りいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('中央監視装置点検', 'building_inspection', '調査のため、建物内に調査員が立ち入りいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('上水受水槽清掃', 'simple_dedicated_water_supply', '貯水槽清掃のため、作業員が立ち入りいたします。断水はありませんが完了後、濁り水が出る場合があります。その際はしばらく流してご使用ください。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('再生水受水槽清掃', 'simple_dedicated_water_supply', '貯水槽清掃のため、作業員が立ち入りいたします。断水はありませんが完了後、濁り水が出る場合があります。その際はしばらく流してご使用ください。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('貯湯タンク清掃', 'simple_dedicated_water_supply', '貯水槽清掃のため、マンション内に作業員が立ち入りいたします。断水はありませんが完了後、濁り水が出る場合があります。その際はしばらく流してご使用ください。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('水質検査', 'Investigation', '水質検査のため、建物内に検査員が立ち入りいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('雑用水水質検査', 'Investigation', '水質検査のため、建物内に検査員が立ち入りいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('残留塩素測定', 'Investigation', '測定のため、建物内に調査員が立ち入りいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('ホルムアルデヒド測定', 'Investigation', '測定のため、建物内に調査員が立ち入りいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('空気環境測定', 'Investigation', '環境測定のため、建物内に調査員が立ち入りいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('ねずみ等の調査・防除調査', 'Investigation', '調査のため、建物内に調査員が立ち入りいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('グリーストラップ清掃', 'cleaning_bucket', '清掃のため、建物内に作業員が立ち入りいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('発電設備点検', 'electrical_measurement', '点検のため、建物内に調査員が立ち入りいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('ターンテーブル設備点検', 'mechanical_parking_turntable', '作業状況によっては入出庫に多少お待ち頂く場合がございます。\n入出庫の際は作業員へお声をかけて頂きますよう、お願い致します。\n＊雨天・緊急等の場合　順延する場合があります。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('電子掲示板工事', 'construction_toolbox', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('ガス安全点検', 'construction_toolbox', '点検のため、建物内に作業員が立ち入りいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('アスファルト補修工事', 'construction_involving_sound_vibration', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('植栽工事', 'construction_involving_sound_vibration', '工事のため敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('インターロッキング補修工事', 'construction_involving_sound_vibration', '工事のため敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('ゴミ置場補修工事', 'construction_involving_sound_vibration', '工事のため敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('駐輪場工事', 'construction_involving_sound_vibration', '工事のため敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('外壁補修工事', 'construction_outer wall', '工事のため敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('エントランスドア補修', 'construction_toolbox', '工事のため敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('窓サッシ補修工事', 'construction_toolbox', '工事のため敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('住戸玄関ドア工事', 'construction_toolbox', '工事のため敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('窓ガラス取替工事', 'construction_toolbox', '工事のため敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('エントランスドア調整工事', 'construction_toolbox', '点検のため、建物内に作業員が立ち入りいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('共用部クロス補修工事', 'construction_roller_paint', '点検のため、建物内に作業員が立ち入りいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('エントランス自動ドア工事', 'automatic_doors', '工事のため敷地内に作業員が立ち入り、作業には音と振動を伴います。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('裏口自動ドア工事', 'automatic_doors', '工事のため敷地内に作業員が立ち入り、作業には音と振動を伴います。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('駐輪場自動ドア工事', 'automatic_doors', '工事のため敷地内に作業員が立ち入り、作業には音と振動を伴います。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('照明取替工事', 'exchange_light_battery', '取替作業のため敷地内に作業員が立ち入ります');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('エントランス照明取替工事', 'exchange_light_battery', '取替作業のため敷地内に作業員が立ち入ります');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('照明器具メンテナンス作業', 'exchange_light_battery_2', '取替作業のため敷地内に作業員が立ち入ります');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('エレベーター改修工事', 'elevator_inspection', '点検中はエレベーター停止致します。\nご不便をおかけします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('住宅玄関ドア枠塗装工事', 'construction_roller_paint', '工事終了後は、塗装に気を付けてください');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('玄関ドア取替工事', 'construction_toolbox', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('外壁タイル補修工事', 'construction_building_large_scale', '工事のため敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('外壁塗装工事', 'construction_roller_paint', '工事のため敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('床タイル補修工事', 'construction_involving_sound_vibration', '工事のため敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('宅配ボックス修理', 'delivery_box_stop_using', '作業状況によっては入出庫に多少お待ち頂く場合がございます。\n入出庫の際は点検員へお声をかけて頂きますよう、お願い致します。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('宅配ボックス設置工事', 'delivery_box', '作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('インターホンメンテンス作業', 'construction_involving_sound_vibration', '作業のため、建物内に作業員が立ち入りいたします　工事中に警報等が鳴る場合もございます');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('住戸インターホン取替作業', 'construction_involving_sound_vibration', '作業のため、建物内に作業員が立ち入りいたします　工事中に警報等が鳴る場合もございます');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('避雷針工事', 'construction_spanner', '工事のため敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('避雷針調査', 'building_inspection', '調査のため、屋上、建物内に作業員が立ち入りいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('受水槽メンテナンス工事', 'construction_spanner', 'メンテナンス作業のため敷地内に作業員が立ち入ります');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('受水槽ボールタップ取替作業', 'construction_toolbox', 'メンテナンス作業のため敷地内に作業員が立ち入ります');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('受水槽塗装工事', 'construction_roller_paint', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('受水槽取替工事', 'construction_involving_sound_vibration', '断水中は蛇口を閉めて下さい。断水中に蛇口を開けると、閉め忘れて漏水事故の恐れがあります。断水前に飲料水等の必要な水の確保をお願いします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('メールボックス取替工事', 'construction_toolbox', '作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('メールボックス更新工事', 'construction_toolbox', '工事中皆様にご不便をおかけいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('メールボックス部品取替作業', 'construction_toolbox', 'メンテナンス作業のため敷地内に作業員が立ち入ります');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('排水管更新工事', 'construction_spanner', '作業には音と振動を伴います。工事中、水を流すことができません。皆様にご不便をおかけいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('共用部　鳩ネット取付工事', 'construction_involving_sound_vibration', '共用部のベランダに鳩ネット取付けます　工事中は、ﾌﾟﾗｲﾊﾞｼｰ保護のためベランダの窓を閉めてください');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('害虫駆除調査', 'Investigation', '調査のため、建物内に調査員が立ち入りいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('害虫駆除消毒', 'disinfection', '消毒中皆様にご不便をおかけいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('通路特別清掃', 'high_pressure_cleaning_2', '床面が滑りやすくなっている場合があります。ご通行の際はご注意下さい。一時的に通行をご遠慮いただく事もございます。ご協力お願いします。\n＊雨天などの理由で、清掃日時を変更させて頂く場合もございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('通路　階段特別清掃', 'high_pressure_cleaning_2', '床面が滑りやすくなっている場合があります。ご通行の際はご注意下さい。一時的に通行をご遠慮いただく事もございます。ご協力お願いします。\n＊雨天などの理由で、清掃日時を変更させて頂く場合もございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('階段特別清掃', 'high_pressure_cleaning', '床面が滑りやすくなっている場合があります。ご通行の際はご注意下さい。一時的に通行をご遠慮いただく事もございます。ご協力お願いします。\n＊雨天などの理由で、清掃日時を変更させて頂く場合もございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('共用廊下床シート工事', 'exchange_corridor', '工事のため敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('感知器取替工事', 'fire_exchange', '取替作業のため敷地内に作業員が立ち入ります');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('防犯カメラ工事', 'surveillance_camera_installation_work', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('侵入防護柵工事', 'electrical_measurement', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('セキュリティ工事', 'construction_toolbox', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('出入口シャッター工事', 'construction_toolbox', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。皆様のご理解をお願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('屋内防火シャッター工事', 'construction_toolbox', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。皆様のご理解をお願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('屋外防火シャッター工事', 'construction_toolbox', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。皆様のご理解をお願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('消火ポンプメンテナンス', 'construction_spanner', '取替作業のため敷地内に作業員が立ち入ります');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('排水ポンプ取替工事', 'construction_spanner', '工事のため作業員が出入りいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('消防ホース取替', 'construction_toolbox', '取替作業のため敷地内に作業員が立ち入ります');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('消防ホース耐圧試験', 'construction_toolbox', '耐圧試験のためマンション内に作業員が立ち入ります。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('屋上看板LED取替工事', 'construction_building_large_scale', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('共用部照明LED変更工事', 'exchange_light_battery', '工事のためマンション敷地内に作業���が立ち入ります。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('照明器具更新工事', 'exchange_light_battery', '照明器具取替のためマンション敷地内に作業員が立ち入ります。また物の搬入のため車両を駐車いたしますので、皆様のご理解をお願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('衛星アンテナ取替工事', 'construction_television_equipment', 'アンテナ工事に伴い、一時テレビが映らない場合があります。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('テレビ視聴設備調査', 'building_inspection', 'テレビ視聴設備調査のため　マンション敷地内に作業員が立ち入ります。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('住戸玄関ドア枠塗装', 'construction_roller_paint', '塗装工事のためマンション敷地内に作業員が立ち入ります。塗装部分には乾くまで触らないようお願いします。、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('共用ドア塗装工事', 'construction_roller_paint', '塗装工事のためマンション敷地内に作業員が立ち入ります。塗装部分には乾くまで触らないようお願いします。、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('エレベータドア塗装工事', 'construction_roller_paint', '塗装工事のためマンション敷地内に作業員が立ち入ります。塗装部分には乾くまで触らないようお願いします。、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('自動火災報知更新工事', 'construction_toolbox', '工事中に、インターホンが使用できないﾊ場合がございます。試験のため、警報等が鳴る場合がございます。皆様にご不便をおかけいたします');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('消火器取替', 'fire_extinguisher_explain', '作業のためマンション内に作業員が出入りいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('ゴミ置場改修工事', 'construction_roller_paint', '工事のため敷地内に作業員が立ち入り、作業には音と振動を伴います。皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('外構工事', 'construction_roller_paint', '工事のため敷地内に作業員が立ち入り、作業には音と振動を伴います。皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('給水管更新工事', 'construction_spanner', '断水中は蛇口を閉めて下さい。断水中に蛇口を開けると、閉め忘れて漏水事故の恐れがあります。断水前に飲料水等の必要な水の確保をお願いします。トイレご排水にはお風呂の汲み置きが有効です。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('電気設備工事', 'electrical_measurement', '取替作業のため敷地内に作業員が立ち入ります');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('電気設備取替工事', 'construction_toolbox', '工事のためマンション敷地内に作業員が立ち入り、作業には音と振動を伴います。皆様のご理解をお願いいたします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('消火用ボックス塗装工事', 'painting_water_pipe', '塗装工事のためマンション敷地内に作業員が立ち入ります。塗装部分には乾くまで触らないようお願いします。、皆様のご理解をお願いいたします。雨天のため順延する場合がございます。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('給水ポンプ更新工事(断水）', 'water_activator_construction', '断水中は蛇口を閉めて下さい。断水中に蛇口を開けると、閉め忘れて漏水事故の恐れがあります。断水前に飲料水等の必要な水の確保をお願いします。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('防鳩工事のお知らせ', 'protect_balcony_from_birds', 'お部屋ののベランダで工事を行います。作業には音と振動を伴います。');
INSERT INTO signage_master_inspection_types (inspection_name, template_no, default_text) VALUES ('ハトネット工事のお知らせ', 'protect_balcony_from_birds_2', 'お部屋ののベランダで工事を行います。作業には音と振動を伴います。');